name: Atualizar Estatísticas do WakaTime

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  update-waka:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Atualizar Estatísticas do WakaTime
      uses: athul/waka-readme@v2
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Atualização automática das estatísticas do WakaTime" || echo "Nada para atualizar"
        git push